### ISSUE TITLE
Add receivers

### ISSUE THREAD

**Issue by jo** [jo/pouch-box#1]

**Comment by trokster** [comment]
Add doc creator to list of receivers ? This way, you can use a simple filter to replicate data across user DBs in one db per user setups.

**Comment by jo** [comment]
Currently the public key of the creator is already in the doc:

``` json
{
  "receivers": {
    "2XiwPX1U6pKPitmhyeubV9g4YYxtIxNfMNE6B5keEmg=": {
      "nonce": "pSquTTn+/I7REorstK6hSYeKizajtu65",
      "encryptedKey": "GXEfX7V3IwA0izAAJ3HIRCzxDFIUfxMq82QO49ITwKzbi+S+5TanJ/9ubmxOUyBh"
    }
  }
}
```

And we already have a simple view in place to list all [docs decrypted for a specific receiver](https://github.com/jo/pouch-box/blob/master/lib/ddoc.js#L8).

What I mean with this issue is my plan to support encryption for many receivers. Currently its restricted to one - the creator.

**Comment by trokster** [comment]
Ah OK, thought you already had implemented receivers :) ( just joined :) )

**Comment by jo** [comment]
Its just three days old ;)
