### ISSUE TITLE
Security considerations

### ISSUE THREAD

**Issue by trokster** [jo/pouch-box#10]
Hi there :)

Currently I am using the following setup:
- one user per couch
- session key derived by your session algorithm to pass to DB creation which in turn generates DB key/pass.

However, I would like the couch admin never to have the possibility of decrypting a user encrypted document not meant for him/her. The only way I see this work is by adding another password for the database itself, independent of login/password that could appear in couchdb logs.

Any thoughts appreciated :)

--troks

**Comment by jo** [comment]
You should use different keys for db authentication and encryption.

**Comment by trokster** [comment]
thought so, ta :)
